"""Category definitions used both to seed the DB and to classify tickets."""

from dataclasses import dataclass, field


@dataclass(frozen=True)
class CategorySpec:
    slug: str
    name: str
    description: str
    color: str
    keywords: tuple[str, ...]
    prototypes: tuple[str, ...]
    tags: tuple[str, ...] = field(default_factory=tuple)


CATEGORY_SPECS: tuple[CategorySpec, ...] = (
    CategorySpec(
        slug="billing",
        name="Facturación",
        description="Cobros, facturas, reembolsos y planes.",
        color="#d4a853",
        keywords=(
            "invoice",
            "billing",
            "charge",
            "refund",
            "payment",
            "subscription",
            "plan",
            "factura",
            "cobro",
            "reembolso",
            "pago",
            "tarjeta",
            "precio",
            "cargo",
            "suscripción",
            "recibo",
        ),
        prototypes=(
            "I was charged twice for my monthly subscription and need a refund.",
            "The invoice amount does not match our contracted plan.",
            "Please update the credit card on file for billing.",
            "Me cobraron dos veces la suscripción mensual, necesito un reembolso.",
            "La factura no coincide con el plan contratado.",
            "Quiero cambiar el método de pago y el recibo de este mes.",
        ),
        tags=("invoice", "refund", "subscription"),
    ),
    CategorySpec(
        slug="technical",
        name="Incidente técnico",
        description="Errores, caídas, bugs y degradación del servicio.",
        color="#c45c4a",
        keywords=(
            "error",
            "bug",
            "crash",
            "timeout",
            "500",
            "outage",
            "down",
            "broken",
            "fail",
            "latency",
            "caído",
            "falla",
            "error",
            "no carga",
            "lentitud",
            "excepción",
            "timeout",
            "no funciona",
        ),
        prototypes=(
            "The dashboard crashes with a 500 error after login.",
            "API requests are timing out and the service looks down.",
            "A production bug is breaking file uploads for all users.",
            "El panel se cae con error 500 después de iniciar sesión.",
            "Las peticiones a la API dan timeout y el servicio parece caído.",
            "Hay un bug en producción: no se pueden subir archivos.",
        ),
        tags=("bug", "outage", "error"),
    ),
    CategorySpec(
        slug="feature",
        name="Solicitud de función",
        description="Mejoras, ideas de producto y nuevos flujos.",
        color="#6b8f71",
        keywords=(
            "feature",
            "enhancement",
            "would be nice",
            "roadmap",
            "suggestion",
            "improvement",
            "función",
            "mejora",
            "podrían",
            "sería útil",
            "agregar",
            "nueva funcionalidad",
            "wishlist",
        ),
        prototypes=(
            "Could you add CSV export to the reports page?",
            "Feature request: dark mode and saved filters on the inbox.",
            "It would help if we could assign tickets to a team queue.",
            "¿Pueden agregar exportación CSV en los reportes?",
            "Solicitud de función: modo oscuro y filtros guardados.",
            "Sería útil poder asignar tickets a una cola de equipo.",
        ),
        tags=("enhancement", "product"),
    ),
    CategorySpec(
        slug="account",
        name="Acceso a cuenta",
        description="Login, permisos, 2FA y recuperación de usuario.",
        color="#5b7fa6",
        keywords=(
            "login",
            "password",
            "reset",
            "2fa",
            "mfa",
            "sso",
            "permission",
            "locked",
            "invite",
            "usuario",
            "contraseña",
            "acceso",
            "iniciar sesión",
            "permisos",
            "bloqueada",
            "invitación",
            "cuenta",
        ),
        prototypes=(
            "I cannot log in after the password reset email.",
            "Please grant editor access to our new teammate.",
            "The account is locked and 2FA codes are not arriving.",
            "No puedo iniciar sesión después de restablecer la contraseña.",
            "Necesito permisos de editor para un compañero nuevo.",
            "La cuenta está bloqueada y no llegan los códigos de 2FA.",
        ),
        tags=("login", "permissions", "2fa"),
    ),
    CategorySpec(
        slug="security",
        name="Seguridad",
        description="Accesos sospechosos, fugas y cumplimiento.",
        color="#8b5e83",
        keywords=(
            "security",
            "breach",
            "leak",
            "phishing",
            "suspicious",
            "unauthorized",
            "vulnerability",
            "cve",
            "seguridad",
            "filtración",
            "sospechoso",
            "no autorizado",
            "vulnerabilidad",
            "incidente",
        ),
        prototypes=(
            "We detected unauthorized logins from an unknown country.",
            "Possible data leak: customer emails appeared on a public paste.",
            "Please review a suspected phishing attempt against our admins.",
            "Detectamos inicios de sesión no autorizados desde otro país.",
            "Posible filtración: aparecieron emails de clientes en un paste público.",
            "Revisen un intento de phishing contra administradores.",
        ),
        tags=("incident", "access", "leak"),
    ),
    CategorySpec(
        slug="general",
        name="Consulta general",
        description="Preguntas de uso, onboarding y documentación.",
        color="#8a8d82",
        keywords=(
            "how do i",
            "how to",
            "question",
            "docs",
            "help",
            "onboarding",
            "cómo",
            "pregunta",
            "ayuda",
            "documentación",
            "duda",
            "dónde",
            "tutorial",
        ),
        prototypes=(
            "How do I invite teammates and share a workspace?",
            "Where can I find the API documentation for webhooks?",
            "Quick question about onboarding a new department.",
            "¿Cómo invito compañeros y comparto un workspace?",
            "¿Dónde está la documentación de la API de webhooks?",
            "Duda rápida sobre el onboarding de un área nueva.",
        ),
        tags=("docs", "how-to"),
    ),
)

SPEC_BY_SLUG = {spec.slug: spec for spec in CATEGORY_SPECS}
